@endpoint = https://kdspwuf7yj.execute-api.us-east-1.amazonaws.com/prod/

GET {{endpoint}}/hello/
###


GET {{endpoint}}/spaces
###

GET {{endpoint}}/spaces?spaceId=0ad886e9-17d9-4d55-8af2-d2766317e610
###

POST {{endpoint}}/spaces/
Content-Type: application/json

{
    "location": "London",
    "name": "Best location"
}
###